language: python
python:
- '2.7'
script:
- cd src
- python test_group_by_allele.py
- python check_allele_table.py ../output/b38/single/clinvar_alleles.single.b38.tsv.gz
- python check_allele_table.py ../output/b38/multi/clinvar_alleles.multi.b38.tsv.gz
- python check_allele_table.py ../output/b37/single/clinvar_alleles.single.b37.tsv.gz
- python check_allele_table.py ../output/b37/multi/clinvar_alleles.multi.b37.tsv.gz
